<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap4\ActiveForm;
use kartik\grid\GridView;
use yii\widgets\Pjax;
use yii\bootstrap4\Modal;
use common\models\master\MasterRole;
use miloschuman\highcharts\Highcharts;
use bc\models\UpsrlmFrameworkValidation;
use common\models\User;
use bc\modules\training\models\RsetisBatchParticipants;
use bc\models\transaction\BcTransaction;

/* @var $this yii\web\View */
/* @var $searchModel bc\models\UpsrlmFrameworkValidationSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Framework of reporting & e-validation of deliverables of BC-technology development ';
//$this->params['breadcrumbs'][] = $this->title;
$class = 'd-none';
if (isset(Yii::$app->user->identity->role) and in_array(Yii::$app->user->identity->role, [MasterRole::ROLE_ADMIN, MasterRole::ROLE_SUPER_ADMIN, MasterRole::ROLE_RSETIS_STATE_UNIT, MasterRole::ROLE_RSETIS_DISTRICT_UNIT, MasterRole::ROLE_MD, MasterRole::ROLE_DC_NRLM, MasterRole::ROLE_BACKEND_OPERATOR, MasterRole::ROLE_SPM_FI_MF])) {
    $class = 'show';
}
?>
<div class="row">
    <div class="col-xl-12">
        <div id="panel-1" class="panel">
            <div class="panel-hdr" style="color:#006cfa;text-align: center">
                <h1 style="color:#006cfa;text-align: center;margin-top: 0.5rem;">
<?= $this->title ?>
                </h1>
                <div class="panel-toolbar">
                    <!--
                                        <button class="btn btn-panel waves-effect waves-themed" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                                        <button class="btn btn-panel waves-effect waves-themed" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                                                            <button class="btn btn-panel waves-effect waves-themed" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>-->
                </div>
            </div>
            <div class="panel-container show">
                <div class="panel-content">

                    <!--                    <div class="col-xl-12">
                                            <h2>Framework of reporting & e-validation of deliverables of BC-technology development </h2>
                    
                                        </div>-->
                    <div class="col-xl-12">
                        <h3 style="text-align: center;text-decoration: underline;color:#009">  Particulars on key milestones & action on e-validation </h3>
                        <table class="table table-striped table-bordered table-condensed table-hover">
                            <tr>
                                <th style="color:#111111;font-size: .9rem; width:12%;font-weight: bold">Col. 3: Starting Date</th> 
                                <td style="width:36%">Testified by technology footprint, the starting date for technology service/ deliverable is system-generated. </td>
                                <th style="color:#111111;font-size: .9rem; width:12%;font-weight: bold">Col. 4: Operational Stage</th> 
                                <td style="width:36%">15-day operational rollout and user-reports generated by at least 50 users/ 100 instances is considered as ‘Fully operational’. From inception to the stage of “Fully operational” is termed as “Rollout”. Both the reporting options are system generated. </td>
                            </tr> 
                            <tr>
                                <th style="color:#111111;font-size: .9rem;font-weight: bold">Col. 5: Current Status</th> 
                                <td>As data gets populated by host of users at the operational level, system-generated ‘Current status’ is automatically reported.</td>
                                <th style="color:#111111;font-size: .9rem;font-weight: bold">Col. 6: E-validation by UPSRLM</th> 
                                <td>As MD UPSRLM finds the technology service showing clear signs of a particular deliverable “fully operational”, tapping the ‘validate’ radio/ check-button would throw a system-generated email to (a) M/S Microsoft Consultancy, (b) Triline (TSA), copies marked to (c) MD-UPSRLM, (d) CRD and (e) ACS-RD. </td>
                            </tr> 
                        </table>
                    </div>
                    <hr/>
                    <div class="row mb-3"></div>
                    <div class="col-xl-12 mt-3">
                        <h3 style="text-align: center;text-decoration: underline;color:#009">E-validation based on user-generated reports</h3>
                        <h4 style="text-align: center;">vide columns 3, 4 and 5 as per updated status of deliverables mandated under BMGF-MSC MoU with Triline (Technology Support Agency_ TSA)</h4>

                        <div id="grid-data-container" class="table-responsive kv-grid-container">
                            <table class="table table-striped table-bordered table-condensed table-hover kv-grid-table kv-table-wrap">
                                <thead>
                                    <tr style="font-size: .9rem;font-weight: 600;text-align: center; background-color: #cccccc;vertical-align:middle">	
                                        <th rowspan="2" class="kv-grid-group-header grid-data" data-group-key="26789841" data-col-seq="0" style="width: 19.99%;vertical-align:middle">BC Sakhi technology development: <span style="font-weight:bold">Key components</span></th><th rowspan="2"  class="kv-grid-group-header grid-data" data-group-key="532e22d1" data-col-seq="1" style="width: 19.99%;vertical-align:middle;"><span style="font-weight:bold">Deliverables</span> <br/>(As per MSC-Triline MoU; to be read with column 1)</th></th>
                                        <th class="text-center warning" colspan="4" style="width: 59.93%;vertical-align:middle"><span style="font-weight:bold">Key milestones & e-validation of deliverables</span></th>
                                    </tr>
                                    <tr style="font-size: .9rem;font-weight: 600;text-align: center;background-color: #cccccc"><th data-col-seq="2" style="width: 22.06%;"><span style="font-weight:bold">Start-date</span></th><th data-col-seq="3" style="width: 11.38%;"><span style="font-weight:bold">Operational Status</span> <br><span>(Rollout/ Fully operational)</span></th><th data-col-seq="4" style="width: 13.7%;"><span style="font-weight:bold">Current status</span><br><span>(Service reported for no. of BCs / Users)</span></th><th data-col-seq="5" style="width: 12.8%;"><span style="font-weight:bold">E-validation by UPSRLM</span></th></tr>

                                    <tr style="background-color: #c5eec1;font-size: .9rem;font-weight: 600;padding: 0.05rem;text-align: center"><th style="padding: 0.05rem;">1</th><th style="padding: 0.05rem;">2</th><th style="padding: 0.05rem;">3</th><th style="padding: 0.05rem;">4</th><th style="padding: 0.05rem;">5</th><th style="padding: 0.05rem;">6</th></tr>
                                </thead>
                                <tbody>
                                    <tr class="grid-data" data-key="1"><td class="grid-data kv-grid-group kv-group-even" style="width: 20%;vertical-align: top" data-col-seq="0" data-group-key="26789841" data-odd-css="kv-group-odd" data-even-css="kv-group-even">-</td><td class="grid-data kv-grid-group kv-group-even" style="width: 20%;vertical-align: top;background-color: #cccccc;" data-col-seq="1" data-group-key="532e22d1" data-odd-css="kv-group-odd" data-even-css="kv-group-even">1. Start-up activities/ developing and activating portal. Enable architecture on portal</td><td class="grid-data" data-col-seq="2"><span style="color:#00bcd4">May 28, 2020</span></td><td class="grid-data" data-col-seq="3">-</td><td class="grid-data" data-col-seq="4">-</td><td class="grid-data" data-col-seq="5" style="background-color: #cccccc"></td></tr>
                                    <tr class="grid-data" data-key="2"><td class="grid-data kv-grid-group kv-group-odd" style="width: 20%;vertical-align: top" data-col-seq="0" data-group-key="26789841" data-odd-css="kv-group-odd" data-even-css="kv-group-even">Android application development for BC Sakhi “identification, pre-selection and shortlisting” process management (No. of BC applications received)</td><td class="grid-data kv-grid-group kv-group-odd" style="width: 20%;vertical-align: top;background-color: #cccccc;" data-col-seq="1" data-group-key="532e22d1" data-odd-css="kv-group-odd" data-even-css="kv-group-even">2. Complete operationalization of  the said processes.</td><td class="grid-data" data-col-seq="2">Date of first application reported: <span style="color:#00bcd4">June 12, 2020</span></td><td class="grid-data" data-col-seq="3">Fully operational</td><td class="grid-data" data-col-seq="4">3,59,366</td><td class="grid-data" style="background-color: #cccccc" data-col-seq="5">
                                            <?php
                                            $model2 = UpsrlmFrameworkValidation::findOne(2);
                                            $html2 = '';
                                            if ($model2->validation_status) {
                                                $html2 .= 'Validated by';
                                            }
                                            if ($model2->validation_by) {
                                                $html2 .= isset($model2->by) ? ' ' . $model2->by->name : '';
                                            }
                                            if ($model2->validation_datetime) {
                                                $html2 .= '<br/>' . 'Time ' . $model2->validation_datetime;
                                            }
                                            ?>
                                            <?=
                                            $model2->validation_status ? $html2 : Html::a('<span class="fal fa-check">Validate</span>', ['/md/validation/framework', 'id' => $model2->id], [
                                                        'title' => 'Validate',
                                                        'data-pjax' => "0",
                                                        'class' => 'btn  btn-info ' . $class,
                                                        'data-confirm' => 'Are you sure to validate the deliverable? This action can not be undone.',
                                                        'data-method' => 'POST',
                                            ]);
                                            ?>

                                        </td></tr>
                                    <tr class="grid-data" data-key="3"><td class="grid-data kv-grid-group kv-group-even" style="width: 20%;vertical-align: top" data-col-seq="0" data-group-key="26789841" data-odd-css="kv-group-odd" data-even-css="kv-group-even" rowspan="4">Web-based BC Sakhi management application for officials of UPSRLM (75+1), RSETI (72+3) and partner agencies (6). Web-based reporting of Police verification (58,675).</td><td class="grid-data kv-grid-group kv-group-even" style="width: 20%;vertical-align: top;background-color: #cccccc;" data-col-seq="1" data-group-key="532e22d1" data-odd-css="kv-group-odd" data-even-css="kv-group-even" rowspan="4">3. Upon completion and acceptance of modules by UPSRLM manifested in operational roll out of the same</td><td class="grid-data" data-col-seq="2">UPSRLM _ MD &amp; DC-NRLM: <span style="color:#00bcd4">December 14, 2020</span></td><td class="grid-data" data-col-seq="3">Fully operational</td><td class="grid-data" data-col-seq="4"><?= common\helpers\Utility::numberIndiaStyle(User::find()->where(['role' => [MasterRole::ROLE_MD, MasterRole::ROLE_DC_NRLM]])->andWhere(['status' => User::STATUS_ACTIVE])->count()) ?></td><td class="grid-data" data-col-seq="5" style="background-color: #cccccc">
                                            <?php
                                            $model3 = UpsrlmFrameworkValidation::findOne(3);
                                            $html3 = '';
                                            if ($model3->validation_status) {
                                                $html3 .= 'Validated by';
                                            }
                                            if ($model3->validation_by) {
                                                $html3 .= isset($model3->by) ? ' ' . $model3->by->name : '';
                                            }
                                            if ($model3->validation_datetime) {
                                                $html3 .= '<br/>' . 'Time ' . $model3->validation_datetime;
                                            }
                                            ?>
                                            <?=
                                            $model3->validation_status ? $html3 : Html::a('<span class="fal fa-check">Validate</span>', ['/md/validation/framework', 'id' => $model3->id], [
                                                        'title' => 'Validate',
                                                        'data-pjax' => "0",
                                                        'class' => 'btn  btn-info ' . $class,
                                                        'data-confirm' => 'Are you sure to validate the deliverable? This action can not be undone.',
                                                        'data-method' => 'POST',
                                            ]);
                                            ?>
                                        </td></tr>
                                    <tr class="grid-data" data-key="4"><td class="grid-data" data-col-seq="2">RSETI: <span style="color:#00bcd4">December 22, 2020</span></td><td class="grid-data" data-col-seq="3">Fully operational</td><td class="grid-data" data-col-seq="4"><?= common\helpers\Utility::numberIndiaStyle(User::find()->where(['role' => [MasterRole::ROLE_RSETIS_STATE_UNIT, MasterRole::ROLE_RSETIS_DISTRICT_UNIT, MasterRole::ROLE_RSETIS_NODAL_BANK]])->andWhere(['status' => User::STATUS_ACTIVE])->count()) ?></td><td class="grid-data" data-col-seq="5" style="background-color: #cccccc">
                                            <?php
                                            $model4 = UpsrlmFrameworkValidation::findOne(4);
                                            $html4 = '';
                                            if ($model4->validation_status) {
                                                $html4 .= 'Validated by';
                                            }
                                            if ($model4->validation_by) {
                                                $html4 .= isset($model4->by) ? ' ' . $model4->by->name : '';
                                            }
                                            if ($model4->validation_datetime) {
                                                $html4 .= '<br/>' . 'Time ' . $model4->validation_datetime;
                                            }
                                            ?>
                                            <?=
                                            $model4->validation_status ? $html4 : Html::a('<span class="fal fa-check">Validate</span>', ['/md/validation/framework', 'id' => $model4->id], [
                                                        'title' => 'Validate',
                                                        'data-pjax' => "0",
                                                        'class' => 'btn  btn-info ' . $class,
                                                        'data-confirm' => 'Are you sure to validate the deliverable? This action can not be undone.',
                                                        'data-method' => 'POST',
                                            ]);
                                            ?>
                                        </td></tr>
                                    <tr class="grid-data" data-key="5"><td class="grid-data" data-col-seq="2">Partner agencies: <span style="color:#00bcd4">January 20, 2021</span></td><td class="grid-data" data-col-seq="3">Fully operational</td><td class="grid-data" data-col-seq="4"><?= common\helpers\Utility::numberIndiaStyle(User::find()->where(['role' => [MasterRole::ROLE_BANK_DISTRICT_UNIT, MasterRole::ROLE_BANK_FI_PARTNER_DISTRICT_NODAL,MasterRole::ROLE_CORPORATE_BCS]])->andWhere(['status' => User::STATUS_ACTIVE])->count()) ?></td><td class="grid-data" data-col-seq="5" style="background-color: #cccccc">
                                            <?php
                                            $model5 = UpsrlmFrameworkValidation::findOne(5);
                                            $html5 = '';
                                            if ($model5->validation_status) {
                                                $html5 .= 'Validated by';
                                            }
                                            if ($model5->validation_by) {
                                                $html5 .= isset($model5->by) ? ' ' . $model5->by->name : '';
                                            }
                                            if ($model5->validation_datetime) {
                                                $html5 .= '<br/>' . 'Time ' . $model5->validation_datetime;
                                            }
                                            ?>
                                            <?=
                                            $model5->validation_status ? $html5 : Html::a('<span class="fal fa-check">Validate</span>', ['/md/validation/framework', 'id' => $model5->id], [
                                                        'title' => 'Validate',
                                                        'data-pjax' => "0",
                                                        'class' => 'btn  btn-info ' . $class,
                                                        'data-confirm' => 'Are you sure to validate the deliverable? This action can not be undone.',
                                                        'data-method' => 'POST',
                                            ]);
                                            ?>
                                        </td></tr>
                                    <tr class="grid-data" data-key="6"><td class="grid-data" data-col-seq="2">PVR update: <span style="color:#00bcd4">March 01, 2021</span></td><td class="grid-data" data-col-seq="3">Fully operational</td><td class="grid-data" data-col-seq="4"><?= common\helpers\Utility::numberIndiaStyle(RsetisBatchParticipants::find()->joinWith(['participant'])->andWhere(['!=', 'rsetis_batch_participants.status', -1])->andWhere(['srlm_bc_application.pvr_status' => 1])->count()) ?></td><td class="grid-data" data-col-seq="5" style="background-color: #cccccc">
                                            <?php
                                            $model6 = UpsrlmFrameworkValidation::findOne(6);
                                            $html6 = '';
                                            if ($model6->validation_status) {
                                                $html6 .= 'Validated by';
                                            }
                                            if ($model6->validation_by) {
                                                $html6 .= isset($model6->by) ? ' ' . $model6->by->name : '';
                                            }
                                            if ($model6->validation_datetime) {
                                                $html6 .= '<br/>' . 'Time ' . $model6->validation_datetime;
                                            }
                                            ?>
                                            <?=
                                            $model6->validation_status ? $html6 : Html::a('<span class="fal fa-check">Validate</span>', ['/md/validation/framework', 'id' => $model6->id], [
                                                        'title' => 'Validate',
                                                        'data-pjax' => "0",
                                                        'class' => 'btn  btn-info ' . $class,
                                                        'data-confirm' => 'Are you sure to validate the deliverable? This action can not be undone.',
                                                        'data-method' => 'POST',
                                            ]);
                                            ?>
                                        </td></tr>
                                    <tr class="grid-data" data-key="7"><td class="grid-data kv-grid-group kv-group-odd" style="width: 20%;vertical-align: top" data-col-seq="0" data-group-key="26789841" data-odd-css="kv-group-odd" data-even-css="kv-group-even" rowspan="2">Web-based application for managing financial assistance to BC Sakhis (58,000)</td><td class="grid-data kv-grid-group kv-group-odd" style="width: 20%;vertical-align: top;background-color: #cccccc;" data-col-seq="1" data-group-key="532e22d1" data-odd-css="kv-group-odd" data-even-css="kv-group-even" rowspan="2">4. Upon completion and acceptance of the service product by UPSRLM; manifested in operational roll out</td><td class="grid-data" data-col-seq="2">Date of 1st payment of BC support fund made to SHGs: <span style="color:#00bcd4">March 23, 2021</span></td><td class="grid-data" data-col-seq="3">Fully operational</td><td class="grid-data" data-col-seq="4"><?= common\helpers\Utility::numberIndiaStyle(RsetisBatchParticipants::find()->joinWith(['participant'])->andWhere(['!=', 'rsetis_batch_participants.status', -1])->andWhere(['srlm_bc_application.bc_shg_funds_status' => 1])->count()) ?></td>
                                        <td class="grid-data" data-col-seq="5" style="background-color: #cccccc">
                                            <?php
                                            $model7 = UpsrlmFrameworkValidation::findOne(7);
                                            $html7 = '';
                                            if ($model7->validation_status) {
                                                $html7 .= 'Validated by';
                                            }
                                            if ($model7->validation_by) {
                                                $html7 .= isset($model7->by) ? ' ' . $model7->by->name : '';
                                            }
                                            if ($model7->validation_datetime) {
                                                $html7 .= '<br/>' . 'Time ' . $model7->validation_datetime;
                                            }
                                            ?>
                                            <?=
                                            $model7->validation_status ? $html7 : Html::a('<span class="fal fa-check">Validate</span>', ['/md/validation/framework', 'id' => $model7->id], [
                                                        'title' => 'Validate',
                                                        'data-pjax' => "0",
                                                        'class' => 'btn  btn-info ' . $class,
                                                        'data-confirm' => 'Are you sure to validate the deliverable? This action can not be undone.',
                                                        'data-method' => 'POST',
                                            ]);
                                            ?>
                                        </td>
                                    </tr>
                                    <tr class="grid-data" data-key="8"><td class="grid-data" data-col-seq="2">1st instance of Honorarium payment to BCs: <span style="color:#00bcd4">December 22, 2021</span> </td>
<!--                                        <td class="grid-data" data-col-seq="3">-</td>
                                        <td class="grid-data" data-col-seq="4">-</td>-->
                                        <td class="grid-data" data-col-seq="3">Fully operational</td>
                                        <td class="grid-data" data-col-seq="4"><?= common\helpers\Utility::numberIndiaStyle(\bc\modules\selection\models\SrlmBcApplication::find()->select('id')->where(['training_status'=>3,'status'=>2])->andWhere(['>','bc_payment_count',0])->count()) ?></td>
                                        <td class="grid-data" data-col-seq="5" style="background-color: #cccccc">
                                          <?php
                                            $model8 = UpsrlmFrameworkValidation::findOne(8);
                                            $html8 = '';
                                            if ($model8->validation_status) {
                                                $html8 .= 'Validated by';
                                            }
                                            if ($model8->validation_by) {
                                                $html8 .= isset($model8->by) ? ' ' . $model8->by->name : '';
                                            }
                                            if ($model8->validation_datetime) {
                                                $html8 .= '<br/>' . 'Time ' . $model8->validation_datetime;
                                            }
                                            ?>
                                            <?=
                                            $model8->validation_status ? $html8 : Html::a('<span class="fal fa-check">Validate</span>', ['/md/validation/framework', 'id' => $model8->id], [
                                                        'title' => 'Validate',
                                                        'data-pjax' => "0",
                                                        'class' => 'btn  btn-info ' . $class,
                                                        'data-confirm' => 'Are you sure to validate the deliverable? This action can not be undone.',
                                                        'data-method' => 'POST',
                                            ]);
                                            ?>  
                                        </td>
                                    </tr>
                                    <tr class="grid-data" data-key="9" data-last-row="1">
                                        <td class="grid-data kv-grid-group kv-group-even" style="width: 20%;vertical-align: top" data-col-seq="0" data-group-key="26789841" data-odd-css="kv-group-odd" data-even-css="kv-group-even">Web-based BC Sakhi operation management service roll out for UPSRLM officials (75+1) and six empanelled partner agencies.</td>
                                        <td class="grid-data kv-grid-group kv-group-even" style="width: 20%;vertical-align: top;background-color: #cccccc;" data-col-seq="1" data-group-key="532e22d1" data-odd-css="kv-group-odd" data-even-css="kv-group-even">5. On operationalization of 100% users as specified and at least 25% of BC Sakhis be functional &amp; operational on ground.</td><td class="grid-data" data-col-seq="2">1st instance of BC operation (performing bank transaction)/ access to reports: <span style="color:#00bcd4">July 10, 2021</span></td><td class="grid-data" data-col-seq="3">Fully operational</td><td class="grid-data" data-col-seq="4"><?= common\helpers\Utility::numberIndiaStyle(BcTransaction::find()->select('bc_application_id')->distinct()->count()) ?></td>
                                        <td class="grid-data" data-col-seq="5" style="background-color: #cccccc">
                                           <?php
                                            $model9 = UpsrlmFrameworkValidation::findOne(9);
                                            $html9 = '';
                                            if ($model9->validation_status) {
                                                $html9 .= 'Validated by';
                                            }
                                            if ($model9->validation_by) {
                                                $html9 .= isset($model9->by) ? ' ' . $model9->by->name : '';
                                            }
                                            if ($model9->validation_datetime) {
                                                $html9 .= '<br/>' . 'Time ' . $model9->validation_datetime;
                                            }
                                            ?>
                                            <?=
                                            $model9->validation_status ? $html9 : Html::a('<span class="fal fa-check">Validate</span>', ['/md/validation/framework', 'id' => $model9->id], [
                                                        'title' => 'Validate',
                                                        'data-pjax' => "0",
                                                        'class' => 'btn  btn-info ' . $class,
                                                        'data-confirm' => 'Are you sure to validate the deliverable? This action can not be undone.',
                                                        'data-method' => 'POST',
                                            ]);
                                            ?> 
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <?php
//                        GridView::widget([
//                            'dataProvider' => $dataProvider,
//                            'layout' => "{items}",
//                            'tableOptions' => ['class' => 'table table-striped table-bordered table-condensed table-hover'],
//                            'id' => 'grid-data',
//                            'beforeHeader' => [
//                                [
//                                    'columns' => [
//                                        ['content' => '', 'options' => ['colspan' => 2, 'class' => 'text-center warning']],
//                                        ['content' => 'Operational milestone(s) & validation thereof', 'options' => ['colspan' => 4, 'class' => 'text-center warning']],
//                                    ],
//                                    'columns' => [
//                                        ['content' => '', 'options' => ['colspan' => 2, 'class' => 'text-center warning']],
//                                        ['content' => 'Operational milestone(s) & validation thereof', 'options' => ['colspan' => 4, 'class' => 'text-center warning']],
//                                    ],
//                                ]
//                            ],
//                            'columns' => [
//                                [
//                                    'attribute' => 'key_id',
//                                    'header' => 'BC Sakhi technology development: Key components',
//                                    'enableSorting' => false,
//                                    'format' => 'raw',
//                                    'group' => true,
//                                    'contentOptions' => ['style' => 'width: 20%;vertical-align: middle'],
//                                    'value' => function ($model) {
//                                        return isset($model->keyf->key_name) ? $model->keyf->key_name : '-';
//                                    }
//                                ],
//                                [
//                                    'attribute' => 'deliverables_id',
//                                    'header' => 'Deliverables',
//                                    'enableSorting' => false,
//                                    'format' => 'raw',
//                                    'contentOptions' => ['style' => 'width: 20%;vertical-align: middle'],
//                                    'group' => true,
//                                    'value' => function ($model) {
//                                        return isset($model->deli->deliverables) ? $model->deli->deliverables : '';
//                                    }
//                                ],
//                                [
//                                    'attribute' => 'start_date',
//                                    'header' => 'Start-date',
//                                    'enableSorting' => false,
//                                    'format' => 'raw',
//                                    'value' => function ($model) {
//                                        return isset($model->st->start) ? $model->st->start : '-';
//                                    }
//                                ],
//                                [
//                                    'attribute' => 'operational_stage',
//                                    'header' => 'Operational stage <br/><span>(Rollout/ Fully operational)</span>',
//                                    'enableSorting' => false,
//                                    'format' => 'raw',
//                                    'value' => function ($model) {
//                                        return isset($model->ops->stage_name) ? $model->ops->stage_name : '-';
//                                    }
//                                ],
//                                [
//                                    'attribute' => 'current_status',
//                                    'header' => 'Current status<br/><span>(Service reported for no. of BCs)</span>',
//                                    'enableSorting' => false,
//                                    'format' => 'raw',
//                                    'value' => function ($model) {
//                                        return isset($model->ct->ct_name) ? $model->ct->ct_name : '-';
//                                    }
//                                ],
//                                [
//                                    'attribute' => 'validation_by',
//                                    'header' => 'Validation by UPSRLM',
//                                    'enableSorting' => false,
//                                    'format' => 'raw',
//                                    'visible' => isset(Yii::$app->user->identity->role) and in_array(Yii::$app->user->identity->role, [MasterRole::ROLE_ADMIN, MasterRole::ROLE_SUPER_ADMIN, MasterRole::ROLE_RSETIS_STATE_UNIT, MasterRole::ROLE_RSETIS_DISTRICT_UNIT, MasterRole::ROLE_MD, MasterRole::ROLE_DC_NRLM, MasterRole::ROLE_BACKEND_OPERATOR, MasterRole::ROLE_SPM_FI_MF]),
//                                    'value' => function ($model) {
//                                        if (in_array($model->id, [2, 3, 4, 5,6])) {
//                                            $html = '';
//                                            if ($model->validation_status) {
//                                                $html .= 'Validated by';
//                                            }
//                                            if ($model->validation_by) {
//                                                $html .= isset($model->by) ? ' '.$model->by->name : '';
//                                            }
//                                            if ($model->validation_datetime) {
//                                                $html .= '<br/>'.'Time ' . $model->validation_datetime;
//                                            }
//                                            return $model->validation_status ? $html : Html::a('<span class="fal fa fa-sign-in">Validate</span>', ['/md/validation/framework', 'id' => $model->id], [
//                                                        'title' => 'Validate',
//                                                        'data-pjax' => "0",
//                                                        'class' => 'btn  btn-info',
//                                                        'data-confirm' => 'Are you sure you want to validate Key components Deliverables?This action not undone',
//                                                        'data-method' => 'POST',
//                                            ]);
//                                        } else {
//                                            return '';
//                                        }
//                                    }
//                                ],
//                            ],
//                        ]);
                        ?>


                    </div>

                </div>
            </div>
        </div> 
    </div>
</div>
