<?php

namespace bcsakhi\components\widget\timeline;

use yii\base\Widget;

// TimelinesWidget.php
class TimelineWidget extends Widget {

    public $model;

    public function init() {
        parent::init();
    }

    public function run() {
        TimelinesWidgetAsset::register($this->getView());
        $this->model = [
             1 => [
                'time' => 'Jul-Sept 2021',
                'title' => 'Setting financial) market disruption In conclusion Immediate tasks',
                'txt' => '<p class="pb-2">Banking practices have already been disrupted by technology. Slow in its process of change, conventional profitability of the banks is threatened by the potent use of algorithms, big data, blockchain, peer-to-peer lending and crowdsourcing. Meaning, role of intermediary is changing. Banks now face competition
                from other intermediaries in their core business (viz. fintech).</p>
                <p class="pb-2">With the State as an emerging player in capitalizing pro-poor
                financial products and services, the settled financial market
                would see proportionally reciprocal and qualitative change. Not
                just banks, all capital market players would feel the disruption.
                Cost of money would drop with the State infusing capital. Not just
                the BCs as operators, the demand side too would be more
                efficient and assertive in financial interaction than in the past. In
                all probability, financial markets would embrace the disruption -
                - high volumes generated by the transactions of the Self Help Group (SHG) poor,
                high frequency back-to-back loan conversions, would set forth
                robust terms of negotiation with the conventional players.</p>
                <p class="pb-2">Structural preparedness for Financial Institution; with specific aim of reaching out to the unreached, is accomplished. While this document is being finalized, 4,892 Banking Correspondent have been trained and certified by IIBF. Onboarding of the BCs and enabling them to stabilize their
                operations on the ground; make it financially viable, would be an
                ensuing challenge. There are several other short-run milestones
                that UPSRLM would need to achieve; simultaneously stepping
                up efforts towards developing appropriate and pro-poor financial
                products and services. An indicative list of such upcoming tasks
                has been delineated below along a timeline.</p>'
            ],  
             2 => [
                'time' => 'May-Sept 2021',
                'title' => 'Enabling the poor embrace incentive-based financial products',
                'txt' => '<p class="pb-2">Poor suffers from congestion of intermediaries. Often, these intermediaries promise to add value to the trail of business transaction in favour of the poor. While promising so, poor’s low capacity to handle it is referred. Experience suggest, these intermediaries
                make
                significant
                gains
                without
                January 2021
                passing proportional benefits to the poor. Poor remains at the end of the financial trail thereby absorbing costs of all intermediaries;
                hence, buying expensive financial services. Now, an affirmative
                action by the State in the domain of financial inclusion, the
                dynamics would change.</p>
                <p class="pb-2">Poor needs to be incentivized for their effort to end their own
                poverty. State as an enabler, poor is expected to step into an
                ecosystem of financial assistance which is organic, less
                expensive, performance driven and incentivized. Incentives may
                be introduced in terms of (a) interest subvention (making loans
                interest free for repayment discipline), (b) moratorium, (c) risk
                hedging (viz. embedding safety net/ insurance protection), (d)
                automated back-to-back loan conversion, (e) business process financing and many other ways. UPSRLM and its field cadres
                need to be used as propagators and catalysts – informing,
                encouraging and enabling the poor to embrace this change,
                consider these opportunities.</p>'],
            3 => [
                'time' => 'Jan-May 2021',
                'title' => 'Mapping aspirations of the poor',
                'txt' => '<p class="pb-2">Poor’s affinity to technology and its aspirational trajectory are uninformed territories. Within the space of financial operations and outcomes thereof, the BC program would throw nuanced intel about change in poor’s financial behavior along time/ seasonality and priority/ preference. DoRD would access such
                intricate operational intel to be able to empower the poor with
                reciprocal financial & institutional measures. Understanding of
                poor’s aspirations would be a critical input. Digitized instruments
                such as micro-credit plan (e-MCP) would compel a reverse
                bottom-up approach; potentially change operational dynamics
                and workflow on the ground.</p>
                <p class="pb-2">Economic empowerment of the poor through cheap and
                subsidized financial products would impact the bargain of State’s
                service delivery. Along the poor’s increasing economic status,
                service delivery targets by various State departments would
                change. Expectedly, poor’s improving economic status would
                reduce burden of govt. expenses on entitlements and service
                provisions. Aspirations of the poor understood and reciprocated
                with livelihood support and range of financial assistance with
                riders such as moratorium, risk hedging etc. would help catalyze
                such changes.</p>'
            ],
            4 => [
                'time' => 'Apr–Jun 2021',
                'title' => 'Define & roll out appropriate range of financial products',
                'txt' => '<p class="pb-2">Understanding specific need of financing of poor’s livelihoods is important. A study could be an important step to explore and understand typology and attributes of pro-poor financial products and services. DoRD and the partner banks/ FIs could engage in careful designing of products and pilot them jointly. With proven efficacy and viability of such products vis-à-vis banks operational costs; contribution of DoRD could be perceived in terms of subvention and subsiding various pro-poor products. This could be a difficult terrain; however, a pathbreaking initiative expanding and deepening financial services & products to cover the interest of the poor.</p>'
            ],
           
             5 => [
                'time' => 'Jan-Apr 2021',
                'title' => 'Revolutionize digitization amongst poor',
                'txt' => '<p class="pb-2">Driving digitization into the wrong side of the divide; deepening into to the strata of the unreached, is a decisive step forward. Approx. 87% of BC candidates use smartphones. Almost all Self Help Group (SHG) are reported to have access to smartphone with one or some of its members. A BC at the doorstep, mobile-app driven accounting & reporting system and handheld device-operated financial transactions, make an assured and viable case for digitization in the remotest rural locations. All of UPSRLM program staff and community cadres should be engaged in financial and digital literacy campaigns and should create an enabling ecosystem for the poor.</p>
                <p class="pb-2">The <a href="http://upsrlm.org">http://upsrlm.org</a> portal would be another effective vehicle
                for not only spread of financial and digital literacy content, this
                would help track the Self Help Group (SHG)’/ unreached customers’ transition from cash-based to digital transaction. This could help quantify
                effect of financial literacy campaigns undertaken by the banks,
                partner banks/ FIs and UPSRLM.</p>'
            ],
            6 =>
            [
                'time' => 'Jun–Dec 2020',
                'title' => 'Setting structural preparedness',
                'txt' => '<p class="pb-2">The DoRD, GoUP, for the first time in India, initiated endowing an upfront support to FI-operational apparatus. This aimed at deepening of apparatus amongst the poor. From searching potential BC candidates that are firmly grouted in the Self Help Group (SHG), to navigating them through IIBF certification, was the first preparatory step to build a pro-poor FI apparatus.</p>
                <p class="pb-2">A well-grounded FI apparatus seeks to be integrated with banks
                for settlement of financial transactions. DoRD learnt that it needs
                to have banks of its own. Empaneling 6 banks to anchor these
                58,000 BCs was a significant step forward. To empower the
                banks and the whole range of certified BCs, DoRD is mobilizing
                the State’s political will from the top.</p>'
            ],
             7 => [
                'time' => 'Mar-Jun 2020',
                'title' => 'Contesting the normal',
                'txt' => '<p class="pb-2">1. This phase is defined by learning the case of financial inclusion
in India and how it played out globally. In India, history since
1950 show change in FI strategies in quick succession. Large
part of this period, banks attempted FI as per their institutional
norms and practices. RBI spearheading the policy and
regulatory space, assigned operations related to FI to the
discretion of banks.</p>
<p class="pb-2">2. An RBI report in Nov. 2019 brings to notice that nearly 40%
families are still left unreached. Thus far, banks led and
controlled the FI operational process, except that of one and only
external intervention. This intervention came into being in 2016
as National Payments Corporation of India (NPCI) 1-driven technology provision for aadhaar-enabled
payment system (AePS). The AePS payment technology
liberated FI operations from stringent bank-led payment norms
and protocols; however, is ensuring highest standards of safety
and customer protection. It also helped remove conventional
approaches of area- and sub-service area-based banking
approaches. Despite complying with the technology-based
provisions of National Payments Corporation of India (NPCI) , bank-led processes seem yet to respond to
the urgency of reaching the unreached.</p>
<p class="pb-2"> For DoRD, this period was a learning curve. While learning the
technicality of the subject, it was a phase of contesting the normal. The phase helped appreciate the fact that banks as
commercial entities may not be the best vehicle to take FI to the
poor. Also, that the State is mandated to support to the FI
process on the ground and consider affirmative action to aid the
poor and the marginalized. DoRD’s interventions must be in
advantage of the poor _ first, by deepening the FI apparatus and
subsequently through several other measures. While May 21’ 20
announcement of the CM underlined State’s commitment to the
poor; the GO dated June 09’ 20, sent the first vibe of constructive
partnership between banks and the Government, the later
endowing a range of operational costs for the first 6 months</p>'
            ],
           
            
           
           
            
            // 8 => [
            //     'time' => 'Jul.-Sept 21',
            //     'title' => 'In conclusion Immediate tasks ',
            //     'txt' => '<p class="pb-2">Structural preparedness for FI; with specific aim of reaching out
            //     to the unreached, is accomplished. While this document is being
            //     finalized, 4,892 BCs have been trained and certified by IIBF.
            //     Onboarding of the BCs and enabling them to stabilize their
            //     operations on the ground; make it financially viable, would be an
            //     ensuing challenge. There are several other short-run milestones
            //     that UPSRLM would need to achieve; simultaneously stepping
            //     up efforts towards developing appropriate and pro-poor financial
            //     products and services. An indicative list of such upcoming tasks
            //     has been delineated below along a timeline.</p>'
            //     ]
        ];
        return $this->render('timeline', [
                    'model' => $this->model,
        ]);
    }
}

?>